---
- name: Create ARM VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create instance
      register: created_instance
      oracle.oci.oci_compute_instance:
        display_name: "{{ server_name }}"
        compartment_id: "{{ oci_compartment_id }}"
        availability_domain: "{{ availability_domain }}"
        fault_domain: "{{ fault_domain }}"
        shape: "{{ vm_shape }}"
        shape_config:
          memory_in_gbs: "{{ 6 }}"
          ocpus: "{{ 1 }}"
        preserve_boot_volume: false
        agent_config:
          are_all_plugins_disabled: false
          is_management_disabled: false
          is_monitoring_disabled: false
        metadata:
          ssh_authorized_keys: "{{ ssh_authorized_keys }}"
        source_details:
          source_type: "image"
          image_id: "{{ oracle_linux_8_arm_ocid }}"
        create_vnic_details:
          assign_public_ip: "{{ assign_public_ip }}"
          subnet_id: "{{ oci_subnet_id }}"
        freeform_tags:
          deployment: "ansible"
    - name: Instance Details
      ansible.builtin.set_stats:
        data:
          instances: created_instance
      when: created_instance is succeeded
