---
- name: Delete ARM VMs created by Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get instance facts
      register: instance_facts
      oracle.oci.oci_compute_instance_facts:
        compartment_id: "{{ oci_compartment_id }}"
    - name: Get OCIDs
      ansible.builtin.set_fact:
        ocids: "{{ instance_facts | json_query('instances[?freeform_tags.deployment==`ansible` && lifecycle_state!=`TERMINATED`].id') }}"
    - name: Found OCIDs
      ansible.builtin.debug:
        var: ocids
    - name: Delete instances
      oracle.oci.oci_compute_instance:
        compartment_id: "{{ oci_compartment_id }}"
        id: "{{ item }}"
        state: absent
      with_items: "{{ ocids }}"
      register: deleted_instances
      when: (ocids is defined) and (ocids | length > 0)
    - name: Debug deleted instances
      ansible.builtin.debug:
        var: deleted_instances.msg
      when: deleted_instances is succeeded and deleted_instances.msg is defined
