---
- name: Delete K8s Cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Compartment Facts
      oracle.oci.oci_identity_compartment_facts:
        id: "{{ oci_compartment_id }}"
      register: compartment_facts
    - name: Get Compartment
      ansible.builtin.set_fact:
        compartment: "{{ compartment_facts.compartments[0] }}"
    - name: Fail if compartment is not active
      ansible.builtin.fail:
        msg: The compartment is not active
      when: compartment_facts.compartments[0].lifecycle_state != 'ACTIVE'
    - name: Debug Compartment Details
      ansible.builtin.debug:
        msg:
          - "Compartment ID: {{ compartment.id }}"
          - "Compartment Name: {{ compartment.name }}"
          - "Compartment Lifecycle State: {{ compartment.lifecycle_state }}"
    - name: Get Compartment Cluster Facts
      oracle.oci.oci_container_engine_cluster_facts:
        compartment_id: "{{ compartment.id }}"
      register: cluster_facts
    - name: Fail if there are no clusters
      ansible.builtin.fail:
        msg: There are no clusters in this compartment
      when: (cluster_facts.clusters | length < 1)
    - name: Set cluster fact
      ansible.builtin.set_fact:
        cluster: "{{ cluster_facts.clusters[0] }}"
    - name: Debug Compartment Cluster Facts
      ansible.builtin.debug:
        msg:
          - "Cluster ID: {{ cluster.id }}"
          - "Cluster Name: {{ cluster.name }}"
          - "Cluster VCN: {{ cluster.vcn_id }}"
    - name: Delete Cluster
      oracle.oci.oci_container_engine_cluster:
        id: "{{ item.id }}"
        compartment_id: "{{ compartment.id }}"
        state: absent
      with_items: "{{ cluster_facts.clusters }}"

- name: Delete Bastions
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Bastion Facts
      oracle.oci.oci_bastion_facts:
        compartment_id: "{{ compartment.id }}"
      register: bastion_facts
    - name: Debug Bastion Facts
      ansible.builtin.debug:
        msg: "Bastion ID: {{ item.id }}"
      with_items: "{{ bastion_facts.bastions }}"
      when: bastion_facts is succeeded and (bastion_facts.bastions | length > 0)
    - name: Delete Bastions
      oracle.oci.oci_bastion:
        id: "{{ item.id }}"
        compartment_id: "{{ compartment.id }}"
        state: absent
      with_items: "{{ bastion_facts.bastions }}"
      when: bastion_facts is succeeded and (bastion_facts.bastions | length > 0)

- name: Delete Block Storage
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Block Volume Facts
      oracle.oci.oci_blockstorage_volume_facts:
        compartment_id: "{{ compartment.id }}"
      register: block_volume_facts
    - name: Debug Block Volume Facts
      ansible.builtin.debug:
        msg:
          - "Block Volume ID: {{ item.id }}"
      with_items: "{{ block_volume_facts.volumes }}"
    - name: Delete Block Volume
      oracle.oci.oci_blockstorage_volume:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ block_volume_facts.volumes }}"

- name: Delete Load Balancers
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Load Balancer Facts
      oracle.oci.oci_loadbalancer_load_balancer_facts:
        compartment_id: "{{ compartment.id }}"
      register: load_balancer_facts
    - name: Debug Load Balancer Facts
      ansible.builtin.debug:
        msg:
          - "LB ID: {{ item.id }}"
      with_items: "{{ load_balancer_facts.load_balancers }}"
    - name: Delete Load Balancer
      oracle.oci.oci_loadbalancer_load_balancer:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ load_balancer_facts.load_balancers }}"

- name: Delete VCN
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Subnet Facts
      oracle.oci.oci_network_subnet_facts:
        compartment_id: "{{ compartment.id }}"
        vcn_id: "{{ cluster.vcn_id }}"
      register: subnet_facts
    - name: Debug Subnet Facts
      ansible.builtin.debug:
        msg:
          - "Subnet ID: {{ item.id }}"
          - "Subnet CIDR: {{ item.cidr_block }}"
      with_items: "{{ subnet_facts.subnets }}"
    - name: Delete Subnets
      oracle.oci.oci_network_subnet:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ subnet_facts.subnets }}"
    - name: Get Route Table Facts
      oracle.oci.oci_network_route_table_facts:
        compartment_id: "{{ compartment.id }}"
        vcn_id: "{{ cluster.vcn_id }}"
      register: route_table_facts
    - name: Debug Route Table Facts
      ansible.builtin.debug:
        msg:
          - "Route Table ID: {{ item.id }}"
      with_items: "{{ route_table_facts.route_tables }}"
    - name: Purge Route Table Rules
      oracle.oci.oci_network_route_table:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        purge_route_rules: true
        route_rules: []
      with_items: "{{ route_table_facts.route_tables }}"
    - name: Delete Route Tables
      oracle.oci.oci_network_route_table:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ route_table_facts.route_tables }}"
      ignore_errors: true
    - name: Get IGW Facts
      oracle.oci.oci_network_internet_gateway_facts:
        compartment_id: "{{ compartment.id }}"
        vcn_id: "{{ cluster.vcn_id }}"
      register: internet_gateway_facts
    - name: Debug IGW Facts
      ansible.builtin.debug:
        msg:
          - "IGW ID: {{ item.id }}"
      with_items: "{{ internet_gateway_facts.internet_gateways }}"
    - name: Delete IGW
      oracle.oci.oci_network_internet_gateway:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ internet_gateway_facts.internet_gateways }}"
      ignore_errors: true
    - name: Get NATGW Facts
      oracle.oci.oci_network_nat_gateway_facts:
        compartment_id: "{{ compartment.id }}"
        vcn_id: "{{ cluster.vcn_id }}"
      register: nat_gateway_facts
    - name: Debug NATGW Facts
      ansible.builtin.debug:
        msg:
          - "NATGW ID: {{ item.id }}"
      with_items: "{{ nat_gateway_facts.nat_gateways }}"
    - name: Delete NATGW
      oracle.oci.oci_network_nat_gateway:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ nat_gateway_facts.nat_gateways }}"
      ignore_errors: true
    - name: Get Service GW Facts
      oracle.oci.oci_network_service_gateway_facts:
        compartment_id: "{{ compartment.id }}"
        vcn_id: "{{ cluster.vcn_id }}"
      register: service_gateway_facts
    - name: Debug Service GW Facts
      ansible.builtin.debug:
        msg:
          - "Service GW ID: {{ item.id }}"
      with_items: "{{ service_gateway_facts.service_gateways }}"
    - name: Delete Service GW
      oracle.oci.oci_network_service_gateway:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ service_gateway_facts.service_gateways }}"
      ignore_errors: true
    - name: Get LPGW Facts
      oracle.oci.oci_network_local_peering_gateway_facts:
        compartment_id: "{{ compartment.id }}"
        vcn_id: "{{ cluster.vcn_id }}"
      register: lp_gateway_facts
    - name: Debug LPGW Facts
      ansible.builtin.debug:
        msg:
          - "LPGW ID: {{ item.id }}"
      with_items: "{{ lp_gateway_facts.local_peering_gateways }}"
    - name: Delete LPGW
      oracle.oci.oci_network_local_peering_gateway:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ lp_gateway_facts.local_peering_gateways }}"
      ignore_errors: true
    - name: Get Security Lists Facts
      oracle.oci.oci_network_security_list_facts:
        compartment_id: "{{ compartment.id }}"
        vcn_id: "{{ cluster.vcn_id }}"
      register: security_list_facts
    - name: Debug Security Lists Facts
      ansible.builtin.debug:
        msg:
          - "Security List ID: {{ item.id }}"
      with_items: "{{ security_list_facts.security_lists }}"
    - name: Delete Security List
      oracle.oci.oci_network_security_list:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ security_list_facts.security_lists }}"
      ignore_errors: true
    - name: Get DRG Attachment Facts
      oracle.oci.oci_network_drg_attachment_facts:
        compartment_id: "{{ compartment.id }}"
        vcn_id: "{{ cluster.vcn_id }}"
      register: drg_attachment_facts
    - name: Debug DRG Attachment Facts
      ansible.builtin.debug:
        msg:
          - "DRG Attachment ID: {{ item.id }}"
      with_items: "{{ drg_attachment_facts.drg_attachments }}"
    - name: Delete DRG Attachments
      oracle.oci.oci_network_drg_attachment:
        compartment_id: "{{ compartment.id }}"
        id: "{{ item.id }}"
        state: absent
      with_items: "{{ drg_attachment_facts.drg_attachments }}"
      ignore_errors: true
    - name: Delete VCN
      oracle.oci.oci_network_vcn:
        id: "{{ cluster.vcn_id }}"
        compartment_id: "{{ compartment.id }}"
        state: absent

- name: Delete Cluster Compartment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete Compartment
      oracle.oci.oci_identity_compartment:
        id: "{{ compartment.id }}"
        state: absent
