---
- name: Get running VM IPs
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get OCI Compute Instance Facts
      oracle.oci.oci_compute_instance_facts:
        compartment_id: "{{ oci_compartment_id }}"
      register: compute_facts
    - name: Get machine details
      ansible.builtin.set_fact:
        instances: "{{ compute_facts | json_query('instances[?lifecycle_state==`RUNNING`].{\"id\": id,\"primary_private_ip\": primary_private_ip,\"primary_public_ip\": primary_public_ip}') }}"
    - name: Found Instances
      ansible.builtin.debug:
        var: instances
      when: (instances is defined) and (instances | length > 0)
