---
- name: Get running VM IPs
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get OCI Compute Instance Facts
      oracle.oci.oci_compute_instance_facts:
        compartment_id: "{{ oci_compartment_id }}"
      register: compute_facts
    - name: Get machine IP addresses
      set_fact:
        ips: "{{ compute_facts | json_query('instances[?lifecycle_state==`RUNNING`].primary_public_ip') }}"
    - name: Found IP addresses
      debug:
        var: ips
      when: (ips is defined) and (ips | length > 0)
