---
plugin: oracle.oci.oci

# Debug flag
debug: false

# Select regions
# regions:
#   - us-ashburn-1

# Config file options
# config_file: ~/.oci/config
# config_profile: DEFAULT

# Fetch host types
fetch_db_hosts: false
fetch_compute_hosts: true

# Caching
# cache: false
# cache_plugin: jsonfile
# cache_timeout: 7200
# cache_connection: /tmp/oci_inventory
# cache_prefix: oci

# Enable threads to speedup lookup
enable_parallel_processing: true

# Sets the inventory_hostname. Each item is a Jinja2 expression and it gets evaluated on host_vars.
hostname_format_preferences:
  # - "display_name+'.oci.com'"
  - "private_ip"
  - "public_ip"

groups:
  terraform: "'terraform' == freeform_tags.deployment"
  ansible: "'ansible' == freeform_tags.deployment"
