---
- name: Create bastion session
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Ansible bastion
      oracle.oci.oci_bastion_facts:
        compartment_id: "{{ lookup('env', 'OCI_COMPARTMENT_ID') }}"
        bastion_lifecycle_state: ACTIVE
      register: bastion_facts
    - name: Debug Bastions
      debug:
        var: bastion_facts
    - name: Get Ansible bastion OCID
      set_fact:
        bastion_ocid: "{{ bastion_facts | json_query('bastions[?lifecycle_state==`ACTIVE` && freeform_tags.deployment==`ansible`].id | [0]') }}"
        cacheable: false
    - name: Debug Bastion OCID
      debug:
        var: bastion_ocid
    - name: Create session
      oci_bastion_session:
        bastion_id: "{{ bastion_ocid }}"
        target_resource_details:
          session_type: MANAGED_SSH
          target_resource_operating_system_user_name: "{{ target_user_name }}"
          target_resource_id: "{{ target_resource_id }}"
          target_resource_port: "{{ target_resource_port }}"
          target_resource_private_ip_address: "{{ target_resource_private_ip }}"
        key_details:
          public_key_content: "{{ ssh_authorized_keys }}"
        # display_name: display_name_example
        # key_type: PUB
        session_ttl_in_seconds: 300
      when: bastion_ocid is defined