---
- name: Create bastion session
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Ansible bastion
      oracle.oci.oci_bastion_facts:
        compartment_id: "{{ lookup('env', 'OCI_COMPARTMENT_ID') }}"
        bastion_lifecycle_state: ACTIVE
      register: bastion_facts
    # - name: Debug Bastions
    #   debug:
    #     var: bastion_facts
    - name: Get Ansible bastion OCID
      set_fact:
        bastion_ocid: "{{ bastion_facts | json_query('bastions[?lifecycle_state==`ACTIVE` && freeform_tags.deployment==`ansible`].id | [0]') }}"
        cacheable: false
    # - name: Debug Bastion OCID
    #   debug:
    #     var: bastion_ocid
    - name: Get connected host facts
      oracle.oci.oci_compute_instance_facts:
        config_file_location: "{{ lookup('env', 'OCI_CONFIG_FILE') }}"
        config_profile_name: "{{ lookup('env', 'OCI_PROFILE') }}"
        compartment_id: "{{ lookup('env', 'OCI_COMPARTMENT_ID') }}"
        instance_id: "{{ target_resource_id }}"
      register: compute_facts
    # - name: Debug instances
    #   debug:
    #     var: compute_facts
    - name: Get instance private ip
      set_fact:
        instance_ip: "{{ compute_facts | json_query('instances[?lifecycle_state==`RUNNING`].primary_private_ip | [0]') }}"
        cacheable: false
    # - name: Debug instance private IP
    #   debug:
    #     var: instance_ip
    - name: Create session
      oracle.oci.oci_bastion_session:
        display_name: ansiblesession
        bastion_id: "{{ bastion_ocid }}"
        target_resource_details:
          session_type: MANAGED_SSH
          target_resource_operating_system_user_name: "{{ target_user_name }}"
          target_resource_id: "{{ target_resource_id }}"
          target_resource_port: "{{ target_resource_port }}"
          target_resource_private_ip_address: "{{ instance_ip }}"
        key_details:
          public_key_content: "{{ public_key }}"
        # display_name: display_name_example
        # key_type: PUB
        session_ttl_in_seconds: 1800
      register: bastion_session
      when: bastion_ocid is defined and instance_ip is defined
    - name: Debug bastion session
      debug:
        var: bastion_session
    - name: Debug bastion session command
      debug:
        var: bastion_session.session.ssh_metadata.command
    - name: Set command fact
      set_fact:
        extracted_command: "{{ bastion_session.session.ssh_metadata.command }}"
    - name: Extract SSH data
      set_fact:
        ssh_command_with_key: "{{ extracted_command | regex_replace('<privateKey>', '$HOME/.ssh/id_ed25519') }}"
        bastion_hostname: "{{ extracted_command | regex_search('\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}', ignorecase=True) }}"
    - name: Extract proxy command 
      set_fact:
        proxy_command: "{{ ssh_command_with_key | regex_search('(ProxyCommand=.*\")', ignorecase=True) }}"
    - name: Debug SSH command
      debug:
        var: ssh_command_with_key
    - name: Debug bastion hostname
      debug:
        var: bastion_hostname
    - name: Debug proxy command
      debug:
        var: proxy_command
    - name: Add bastion host to inventory
      add_host:
        hostname: "{{ bastion_hostname }}"
        ansible_ssh_common_args: "-o {{ proxy_command }}"
