---
- name: Create Bastion Host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create bastion
      oracle.oci.oci_bastion:
        bastion_type: standard
        state: present
        compartment_id: "{{ lookup('env', 'OCI_COMPARTMENT_ID') }}"
        target_subnet_id: "{{ subnet_id }}"
        name: "{{ bastion_name }}"
        client_cidr_block_allow_list: "{{ allowed_ips }}"
        max_session_ttl_in_seconds: 1800
        freeform_tags: 
          deployment: ansible
