---
- name: Delete VM Instance
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Delete instances
      oracle.oci.oci_compute_instance:
        config_file_location: "{{ lookup('env', 'OCI_CONFIG_FILE') }}"
        config_profile_name: "{{ lookup('env', 'OCI_PROFILE') }}"
        compartment_id: "{{ lookup('env', 'OCI_COMPARTMENT_ID') }}"
        id: "{{ instance_ocid }}"
        state: absent
      register: deleted_instances
    - name: Debug deleted instances
      debug:
        var: deleted_instances.msg
      when: deleted_instances is succeeded and deleted_instances.msg is defined
