---
- name: Create bastion sessions for private servers
  import_playbook: create_bastion_sessions.yml

- name: Update running OCI VMs
  hosts: all_hosts
  become: true
  vars:
    ansible_user: opc
    ssh_public_keys: "{{ ssh_keys }}"
    users: "{{ users }}"
    passwordless_admin: "{{ passwordless_admin }}"
    config_fish: "{{ config_fish }}"
    config_vim: "{{ config_vim }}"
  roles:
    - role: scottharwell.server_setup
