---
- name: Run setup process
  hosts: all_hosts
  become: true
  vars:
    ssh_public_keys:
      - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519_prompt_ios.pub') }}"
    users:
      - name: opc
        admin: true
      - name: scott
        admin: true
    passwordless_admin: true
    config_fish: false
    config_vim: false
  roles:
    - role: scottharwell.server_setup
