---
config_profile_name: DEFAULT
oci:
  vcn_protocols:
    ICMP: "1"
    TCP: "6"
    UDP: "17"
    ICMPv6: "58"
    all: all
vcn:
  cidr_blocks:
    - "172.16.240.0/20"
  display_name: Site to Site VCN
  dns_label: s2svcn
  subnets:
    - display_name: primary
      cidr_block: "172.16.240.0/23"
      prohibit_internet_ingress: true
      prohibit_public_ip_on_vnic: true
      freeform_tags:
        deployment: ansible
        accessibility: private
    - display_name: private
      cidr_block: "172.16.242.0/24"
      prohibit_internet_ingress: true
      prohibit_public_ip_on_vnic: true
      freeform_tags:
        deployment: ansible
        accessibility: private
    - display_name: public
      cidr_block: "172.16.243.0/24"
      prohibit_internet_ingress: false
      prohibit_public_ip_on_vnic: false
      freeform_tags:
        deployment: ansible
        accessibility: public
customer_connectivity:
  drg:
    display_name: S2S VPN DRG
  cpe:
    display_name: GSO CPE
    device_shape: "0c14a129-ce70-43f3-bf07-e980a6784ae8"
    ip_address: "97.75.152.17"
  ip_sec_connection:
    display_name: GSO IPSEC Connection
    routing: STATIC
    ike_version: V1
    shared_secret: change_me
    cpe_local_identifier: 97.75.152.17
    cpe_local_identifier_type: IP_ADDRESS
