---
- name: Create Bastion Host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create bastion
      oracle.oci.oci_bastion:
        bastion_type: standard
        state: present
        compartment_id: "{{ compartment_id }}"
        target_subnet_id: "{{ subnet_id }}"
        name: "{{ bastion_name }}"
        client_cidr_block_allow_list: "{{ allowed_ips }}"
        max_session_ttl_in_seconds: "{{ bastion_ttl }}"
        freeform_tags:
          deployment: ansible
